# Homework Data wrangling with Telco mini dataset

Note เราจะใช้ข้อมูลที่ชื่อว่า telco_mini.csv

ข้อไหนที่ตอบเป็น text อย่าลืมใส่ # ข้างหน้านะคะ

เช่น # ตอบว่ามีหรือไม่มี  # ตอบว่า ไม่มี  เป็นต้น

ให้รัน code ทุกบรรทัด การบ้านคะแนนเต็ม 10 คะแนน (ข้อละ 2 คะแนน)

In [1]:
%matplotlib inline
import pandas as pd

df = pd.read_csv('telco_mini_s.csv')

In [2]:
df.head()

,customerID,Age,gender,SeniorCitizen,Partner,PhoneService,InternetService,StreamingTV,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,65.0,Female,Yes,Yes,No,DSL,No,Month-to-month,Electronic check,29.85,29.85,No
1,5575-GNVDE,31.0,Male,No,No,Yes,DSL,No,One year,Mailed check,56.95,1889.50,No
2,3668-QPYBK,33.0,Male,No,No,Yes,DSL,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,26.0,Male,No,No,No,DSL,No,One year,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,61.0,Female,Yes,No,Yes,Fiber optic,No,Month-to-month,Electronic check,70.70,151.65,Yes

In [3]:
print(df.shape)

(50, 13)

# Exercise 1
จงใช้คำสั่ง .info เพื่อแสดงให้เห็นถึง datatype ของแต่ละ column ของ df

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customerID       50 non-null     object
 1   Age              47 non-null     float64
 2   gender           50 non-null     object
 3   SeniorCitizen    50 non-null     object
 4   Partner          50 non-null     object
 5   PhoneService     50 non-null     object
 6   InternetService  50 non-null     object
 7   StreamingTV      50 non-null     object
 8   Contract         50 non-null     object
 9   PaymentMethod    50 non-null     object
 10  MonthlyCharges   50 non-null     float64
 11  TotalCharges     50 non-null     float64
 12  Churn            50 non-null     object
dtypes: float64(3), object(10)
memory usage: 5.2+ KB

มี column ใดที่มี datatype ไม่เหมาะสมหรือไม่ ถ้ามีให้แปลงเป็น datatype ที่เหมาะสม

In [8]:
# มี

# Exercise 2
จงใช้คำสั่ง .describe เพื่อแสดงให้เห็นถึงค่าสถิติ ของแต่ละ column ของ df ที่เป็น numerical data

In [5]:
df.describe()

             Age  MonthlyCharges  TotalCharges
count  47.000000       50.000000     50.000000
mean   35.680851       67.244000   2320.679000
std    16.183871       28.522323   2333.552125
min    19.000000       18.950000     20.150000
25%    26.500000       49.325000    305.650000
50%    30.000000       67.675000   1685.675000
75%    33.000000       94.187500   3817.337500
max    84.000000      113.250000   7895.150000

# Exercise 3
จงแสดงให้เห็นว่าแต่ละ column มีจำนวน missing data หรือ Nan อยู่กี่ข้อมูล

In [7]:
missing_data_count = df.isnull().sum()
print(missing_data_count)

customerID         0
Age                3
gender             0
SeniorCitizen      0
Partner            0
PhoneService       0
InternetService    0
StreamingTV        0
Contract           0
PaymentMethod      0
MonthlyCharges     0
TotalCharges       0
Churn              0
dtype: int64

# Exercise 4

จงใช้คำสั่ง .mean() แสดงค่าเฉลี่ยของอายุของลูกค้าในชุดข้อมูลนี้

In [11]:
average_age = df['Age'].mean()
print(average_age)

35.680851063829785

# Exercise 5

จงใช้ข้อมูลค่าเฉลี่ยของกลุ่มลูกค้าเพื่อใช้ในการแก้ไข missing value

In [16]:
df['Age'].fillna(average_age, inplace=True)

In [17]:
df.Age.isnull().sum()

0